### ISSUE TITLE
UnboundLocalError: local variable 'referenceName' referenced before assignment

### ISSUE THREAD

**Issue by camilo-monge** [phac-nml/neptune#10]
Hello, I'm trying to run the program and encounter the following error:
`Neptune v1.2.5

Estimating k-mer size ...
k = 19

k-mer Counting...
Submitted 2 jobs.
Traceback (most recent call last):
  File "/home/camilo/miniconda2/bin/neptune-conda", line 10, in <module>
    sys.exit(main())
  File "/home/camilo/miniconda2/lib/python2.7/site-packages/neptune/Neptune.py", line 986, in main
    parse(parameters)
  File "/home/camilo/miniconda2/lib/python2.7/site-packages/neptune/Neptune.py", line 765, in parse
    executeParallel(parameters)
  File "/home/camilo/miniconda2/lib/python2.7/site-packages/neptune/Neptune.py", line 749, in executeParallel
    execute(execution)
  File "/home/camilo/miniconda2/lib/python2.7/site-packages/neptune/Neptune.py", line 655, in execute
    inclusionKMerLocations, exclusionKMerLocations = countKMers(execution)
  File "/home/camilo/miniconda2/lib/python2.7/site-packages/neptune/Neptune.py", line 238, in countKMers
    execution.jobManager.runJobs(jobs)
  File "/home/camilo/miniconda2/lib/python2.7/site-packages/neptune/JobManagerParallel.py", line 138, in runJobs
    self.synchronize(jobs)
  File "/home/camilo/miniconda2/lib/python2.7/site-packages/neptune/JobManagerParallel.py", line 178, in synchronize
    job.get()  # get() over wait() to propagate excetions upwards
  File "/home/camilo/miniconda2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
UnboundLocalError: local variable 'referenceName' referenced before assignment'

I installed using conda and --version seems to be right. I tried to run in both the 2.7 installation and the default conda one. Any help would be appreciated.

**Comment by emarinier** [comment]
This error is likely related to issue #9.

In short, Neptune doesn't check file extensions and it might be assuming a file is FASTA format when the file is actually something else (text, image, etc.).

If you run Neptune on the command line by pointing to directories, they must contain only FASTA files. Does Neptune run correctly if you specify individual files? For example:

```
neptune --inclusion 1.fasta 2.fasta --exclusion 3.fasta 4.fasta --output output_directory
```

**Comment by camilo-monge** [comment]
That was the problem, it seems, thank you
