### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by lskatz** [phac-nml/neptune#8]
My first time trying out Neptune.  I have two fasta files in the inclusion directory and two fasta files in the exclusion directory.  For some reason, it says `No such file or directory` at the end but I don't understand why.

```
neptune --inclusion inclusion --exclusion exclusion --output neptune -p 12; echo $?
Neptune v1.2.5

Estimating k-mer size ...
k = 25

k-mer Counting...
Submitted 4 jobs.
0.1 seconds

k-mer Aggregation...
Submitted 65 jobs.
0.53 seconds

Signature Extraction...
Submitted 2 jobs.
0.03 seconds

Signature Filtering...
Submitted 2 jobs.
Traceback (most recent call last):
  File "/scicomp/home/gzu2/bin/build/neptune-1.2.5/lib/neptune/bin/neptune", line 10, in <module>
    sys.exit(main())
  File "/scicomp/home/gzu2/bin/build/neptune-1.2.5/lib/neptune/lib/python2.7/site-packages/neptune/Neptune.py", line 986, in main
    parse(parameters)
  File "/scicomp/home/gzu2/bin/build/neptune-1.2.5/lib/neptune/lib/python2.7/site-packages/neptune/Neptune.py", line 765, in parse
    executeParallel(parameters)
  File "/scicomp/home/gzu2/bin/build/neptune-1.2.5/lib/neptune/lib/python2.7/site-packages/neptune/Neptune.py", line 749, in executeParallel
    execute(execution)
  File "/scicomp/home/gzu2/bin/build/neptune-1.2.5/lib/neptune/lib/python2.7/site-packages/neptune/Neptune.py", line 676, in execute
    sortedLocations = filterSignatures(execution, candidateLocations)
  File "/scicomp/home/gzu2/bin/build/neptune-1.2.5/lib/neptune/lib/python2.7/site-packages/neptune/Neptune.py", line 558, in filterSignatures
    execution.jobManager.runJobs([inclusionDatabaseJob, exclusionDatabaseJob])
  File "/scicomp/home/gzu2/bin/build/neptune-1.2.5/lib/neptune/lib/python2.7/site-packages/neptune/JobManagerParallel.py", line 138, in runJobs
    self.synchronize(jobs)
  File "/scicomp/home/gzu2/bin/build/neptune-1.2.5/lib/neptune/lib/python2.7/site-packages/neptune/JobManagerParallel.py", line 178, in synchronize
    job.get()  # get() over wait() to propagate excetions upwards
  File "/apps/x86_64/python/2.7.13/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
OSError: [Errno 2] No such file or directory
1
```

**Comment by lskatz** [comment]
I have to mask the genome names but I want to see if I can provide more information.  Contigs <1kbp were filtered out.  Only four genomes total.

```
File               genomeLength  N50     numContigs
inclusion1.fasta   5674478       226345  78 
inclusion2.fasta   5588000       241093  79  
exclusion1.fasta   4672201       117948  56 
exclusion2.fasta   4610441       412485  21
```

**Comment by emarinier** [comment]
Could you tell me if you're running Neptune from a source installation, through Conda, or through Galaxy?

My suspicion is that Neptune is crashing during the BLASTN filtering. In particular, it looks like it's trying to create a BLASTN database:

```
  File "/scicomp/home/gzu2/bin/build/neptune-1.2.5/lib/neptune/lib/python2.7/site-packages/neptune/Neptune.py", line 558, in filterSignatures
    execution.jobManager.runJobs([inclusionDatabaseJob, exclusionDatabaseJob])
```
Which eventually involves running this code: https://github.com/phac-nml/neptune/blob/release/1.2/neptune/Database.py#L165

You may want to verify that wherever Neptune is running, it's able to run the command "makeblastdb". It may be crashing if the command is unavailable. If the command is unavailable, you will either need to install BLASTN or install Neptune using Conda.

Let me know how things go.
